# Generated by Django 3.1.5 on 2021-01-14 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cadastro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cliente', models.CharField(max_length=25, verbose_name='Nome')),
                ('Sobrenome', models.CharField(max_length=30, verbose_name='Sobrenome')),
                ('Data_de_nascimento', models.DateField(max_length=12, verbose_name='Data de nascimento')),
                ('Email', models.EmailField(max_length=20, verbose_name='Email')),
                ('Apelido', models.CharField(max_length=15, null=True, verbose_name='Apelido')),
                ('Observações', models.TextField(max_length=200, null=True, verbose_name='Observações')),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nome', models.CharField(max_length=25, verbose_name='Nome')),
                ('sobrenome', models.CharField(max_length=30, null=True, verbose_name='Sobrenome')),
            ],
        ),
    ]
